---
language: python
python: "2.7"
sudo: required
dist: trusty

before_install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
  - virtualenv venv
  - pip install https://github.com/mvdbeek/maasclient/archive/master.zip
  - make

script:
  - docker network create --subnet=192.168.1.0/24 net1
  - make run -e NET=net1 && sleep 120s
  - make test_api_access

deploy:
  provider: script
  script: make push DOCKER_PASSWORD=$DOCKER_PASSWORD
  on:
    branch: master
