---
language: python
python: "2.7"
sudo: required
dist: trusty

before_install:
  - sudo apt-get install -y debian-keyring debian-archive-keyring
  - sudo add-apt-repository -y ppa:maas/stable
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y python-maas-client docker-engine
  - make

script:
  - docker network create --subnet=192.168.1.0/24 net1
  - make run -e NET=net1 && sleep 120s
  - make test_api_access
